import { bootstrapApplication } from '@angular/platform-browser';
import {
  RouteReuseStrategy,
  provideRouter,
  withPreloading,
  PreloadAllModules,
} from '@angular/router';
import { IonicRouteStrategy, provideIonicAngular } from '@ionic/angular/standalone';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { AppComponent } from './app/app.component';
import { routes } from './app/app.routes';

/** Interceptor de autenticación (401 -> refresh, agrega Authorization y XSRF) */
import { authInterceptor } from './app/core/interceptors/auth/auth.interceptor';

/** === Ionicons: registra solo los íconos que usas === */
import { addIcons } from 'ionicons';
import {
  addOutline,
  alertCircleOutline,
  arrowBack,
  arrowForward,
  arrowUpCircleOutline,
  bagHandleOutline,
  bagOutline,
  basketOutline,
  businessOutline,
  calendarOutline,
  calculatorOutline,
  call,
  callOutline,
  cardOutline,
  cart,
  cashOutline,
  chatbubbleEllipsesOutline,
  chatbubblesOutline,
  checkboxOutline,
  checkmarkCircle,
  checkmarkDoneOutline,
  chevronBackOutline,
  chevronDownOutline,
  chevronForward,
  chevronForwardOutline,
  chevronUpOutline,
  close,
  closeCircleOutline,
  cloudUploadOutline,
  createOutline,
  location,
  create,
  trash,
  trashOutline,
  cubeOutline,
  documentTextOutline,
  expandOutline,
  eye,
  eyeOff,
  eyeOutline,
  heart,
  heartOutline,
  homeOutline,
  hourglassOutline,
  idCard,
  idCardOutline,
  imageOutline,
  informationCircleOutline,
  keyOutline,
  layersOutline,
  leaf,
  leafOutline,
  listOutline,
  locationOutline,
  lockClosedOutline,
  logOutOutline,
  mail,
  mailOutline,
  mapOutline,
  menu,
  notifications,
  notificationsOutline,
  nutritionOutline,
  person,
  personCircle,
  personOutline,
  readerOutline,
  receiptOutline,
  refresh,
  search,
  sendOutline,
  shieldCheckmarkOutline,
  star,
  starHalfOutline,
  starOutline,
  statsChartOutline,
  storefrontOutline,
  swapHorizontalOutline,
  timeOutline,
  trendingUpOutline,
} from 'ionicons/icons';

/** 👇 Importamos y registramos locale español Colombia */
import { registerLocaleData } from '@angular/common';
import localeEsCO from '@angular/common/locales/es-CO';
import { LOCALE_ID } from '@angular/core';

registerLocaleData(localeEsCO, 'es-CO');

// Registra los SVG (evita cargas por URL y quita warnings de iconos no encontrados)
addIcons({
  'add-outline': addOutline,
  'alert-circle-outline': alertCircleOutline,
  'arrow-back': arrowBack,
  'arrow-forward': arrowForward,
  'arrow-up-circle-outline': arrowUpCircleOutline,
  'bag-handle-outline': bagHandleOutline,
  'bag-outline': bagOutline,
  'basket-outline': basketOutline,
  'business-outline': businessOutline,
  'calendar-outline': calendarOutline,
  'calculator-outline': calculatorOutline,
  call,
  'call-outline': callOutline,
  'card-outline': cardOutline,
  cart,
  'cash-outline': cashOutline,
  'chatbubble-ellipses-outline': chatbubbleEllipsesOutline,
  'chatbubbles-outline': chatbubblesOutline,
  'checkbox-outline': checkboxOutline,
  'checkmark-circle': checkmarkCircle,
  'checkmark-done-outline': checkmarkDoneOutline,
  'chevron-back-outline': chevronBackOutline,
  'chevron-down-outline': chevronDownOutline,
  'chevron-forward': chevronForward,
  'chevron-forward-outline': chevronForwardOutline,
  'chevron-up-outline': chevronUpOutline,
  close,
  'close-circle-outline': closeCircleOutline,
  'cloud-upload-outline': cloudUploadOutline,
  'create-outline': createOutline,
  create,
  'cube-outline': cubeOutline,
  'document-text-outline': documentTextOutline,
  'file-text-outline': documentTextOutline,
  'expand-outline': expandOutline,
  eye,
  'eye-off': eyeOff,
  'eye-outline': eyeOutline,
  heart,
  'heart-outline': heartOutline,
  'home-outline': homeOutline,
  'hourglass-outline': hourglassOutline,
  'id-card': idCard,
  'id-card-outline': idCardOutline,
  'image-outline': imageOutline,
  'inbox-outline': mailOutline,
  'information-circle-outline': informationCircleOutline,
  'key-outline': keyOutline,
  'layers-outline': layersOutline,
  leaf,
  'leaf-outline': leafOutline,
  'list-outline': listOutline,
  location,
  'location-outline': locationOutline,
  'lock-closed-outline': lockClosedOutline,
  'log-out-outline': logOutOutline,
  mail,
  'mail-outline': mailOutline,
  'map-outline': mapOutline,
  menu,
  notifications,
  'notifications-outline': notificationsOutline,
  'nutrition-outline': nutritionOutline,
  person,
  'person-circle': personCircle,
  'person-outline': personOutline,
  'reader-outline': readerOutline,
  'receipt-outline': receiptOutline,
  refresh,
  search,
  'send-outline': sendOutline,
  'shield-checkmark-outline': shieldCheckmarkOutline,
  star,
  'star-half-outline': starHalfOutline,
  'star-outline': starOutline,
  'stats-chart-outline': statsChartOutline,
  'storefront-outline': storefrontOutline,
  'swap-horizontal-outline': swapHorizontalOutline,
  'time-outline': timeOutline,
  trash,
  'trash-outline': trashOutline,
  'trending-up-outline': trendingUpOutline,
});

bootstrapApplication(AppComponent, {
  providers: [
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy },
    provideIonicAngular(),
    provideHttpClient(withInterceptors([authInterceptor])),
    provideRouter(routes, withPreloading(PreloadAllModules)),

    /** 👇 Esto asegura que todo Angular use es-CO por defecto */
    { provide: LOCALE_ID, useValue: 'es-CO' },
  ],
});
